# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - postgresql.database:/home/postgres/app
    environment:
      POSTGRES_PASSWORD: postgresql
      POSTGRES_USER: postgresql
    ports:
      - 5432:5432

volumes:
  postgresql.database:
